// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yypowuphmycioiwdmyzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cG93dXBobXljaW9pd2RteXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDE1MjgsImV4cCI6MjA3NDI3NzUyOH0.OA_WW6nd8MeVoSYPCxOfoDVnV-kG-O0nlJ2JT_SS700";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});